FROM python:3.7-slim-stretch
RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential

# Copy app source.
WORKDIR /app/user-service
COPY . .

# Install requirements.
RUN pip install -r requirements.txt
RUN pip install -r test-requirements.txt

# Prepare environment.
ENV FLASK_DEBUG 1

# Start command.
CMD ["sh", "run-tests.sh"]
